services:
  zookeeper:
    image: quay.io/debezium/zookeeper:3.0
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: quay.io/debezium/kafka:3.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  mysql1:
    image: mysql:latest
    container_name: mysql1
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

  connect:
    image: quay.io/debezium/connect:3.0
    container_name: connect
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - CONFIG_STORAGE_REPLICATION_FACTOR=1
      - OFFSET_STORAGE_REPLICATION_FACTOR=1
      - STATUS_STORAGE_REPLICATION_FACTOR=1
    depends_on:
      - kafka
      - mysql1

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=datdepzai
      - MONGO_INITDB_ROOT_PASSWORD=123

  redis:
    image: redis:latest
    container_name: quanhdzredis
    ports:
      - "6379:6379"
    command: --requirepass '789'